#!/usr/bin/env bash

cd /home/m/cure/data
for dir in $(find -type d | sort | uniq); do
	echo "$dir";
	echo "$(find "$dir" -type f | wc -l)";
	echo "Delete y/n?";
	read answer;
	if [[ "$answer" == "y" ]]; 
		then rm -r $dir; 
	fi;
done
