#!/bin/bash

cd ~/structures

shopt -s extglob

keep=3rzy_bms309403_search_space_30_3
stem=3rzy_bms309403
for file in `ls`
do
	case $file in
		$stem*)
	case $file in
		!($keep*)) rm $file;;
	esac;;
esac
done

shopt -u extglob
